version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network
    volumes:
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped

  # Go Application (Service 1)
  service1:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    expose:
      - "8001"
    networks:
      - app-network
    environment:
      - PORT=8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Python Application (Service 2)
  service2:
    build:
      context: ./service_2
      dockerfile: Dockerfile
    expose:
      - "8002"
    networks:
      - app-network
    environment:
      - PORT=8002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs: